services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    restart: unless-stopped
    expose:
      - "8080"
      - "50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
