FROM jenkins/inbound-agent:latest-jdk21

USER root

RUN apt-get update && \
    apt-get install -y \
        docker.io \
        docker-compose-v2 \
        git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins